### ISSUE TITLE
请做个https://w.xiaoshuoxiaapp.cc/的源，谢谢！

### ISSUE THREAD

**Issue by bin698** [xingluo233/BookSource#2]
{
    "bookSourceComment": "https://www.xiaoshuoxiaapp.com/",
    "bookSourceGroup": "✯·常用",
    "bookSourceName": "小说侠网",
    "bookSourceType": 0,
    "bookSourceUrl": "https://w.xiaoshuoxiaapp.cc/",
    "customOrder": 1464,
    "enabled": true,
    "enabledCookieJar": true,
    "enabledExplore": false,
    "exploreUrl": "",
    "lastUpdateTime": 1660784569856,
    "respondTime": 8180,
    "ruleBookInfo": {
      "author": "$..Author",
      "coverUrl": "$..BookImage",
      "init": "",
      "intro": "$..Description",
      "kind": "{{$..CategoryName}}\n{{$..BookStatusStr}}",
      "lastChapter": "$..LastUpdateChapter",
      "name": "$..BookName",
      "tocUrl": "https://w.xiaoshuoxiaapp.cc/book/GetBookAllChapters?bookId={{$..BookId}}@put:{bid:$..BookId}",
      "wordCount": "$..HitCount"
    },
    "ruleContent": {
      "content": "id.chaptercontent@html"
    },
    "ruleExplore": {
      "bookList": ""
    },
    "ruleSearch": {
      "author": "$.Author",
      "bookList": "$.obj[*]",
      "bookUrl": "https://w.xiaoshuoxiaapp.cc//book/getbook?userId=no&bookId={{$.BookId}}",
      "coverUrl": "$.BookImage",
      "intro": "$.Description",
      "name": "$.BookName",
      "wordCount": "$.HitCount"
    },
    "ruleToc": {
      "chapterList": "$.obj[*]",
      "chapterName": "$.chaptername",
      "chapterUrl": "https://w.xiaoshuoxiaapp.cc/book/H5Detail?bookId=@get:{bid}&chapterId={{$.chapterid}}&userId=no&deviceId=578d6ab5-d3e5-4ad8-80a8-b4c6a3d15cdc",
      "updateTime": ""
    },
    "searchUrl": "https://w.xiaoshuoxiaapp.cc/Book/GetBookByKey?key={{key}}&pageIndex={{page}}",
    "weight": 0
  }

**Comment by xingluo233** [comment]
已添加
